[project]
name = "reportseff"
version = "2.10.3"
description= "Tablular seff output"
authors = [
  {name="Troy Comi", email="<troycomi@gmail.com>"}
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
keywords= ["slurm","seff"]
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.3",
]

[project.scripts]
reportseff = "reportseff.console:cli"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[urls]
homepage= "https://github.com/troycomi/reportseff"
repository= "https://github.com/troycomi/reportseff"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "poethepoet>=0.37.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "pytype>=2024.9.13",
    "ruff>=0.15.0",
    "typeguard>=4.4.4",
]

[tool.poe]
executor = { type = "uv" }

[tool.poe.tasks]
format = "ruff format"

checks = ["lint", "audit", "mypy", "pytype"]
lint = "ruff check"
audit = { cmd = "pip-audit", executor = {with = ["pip-audit"]}}
mypy = "mypy ."
pytype = "pytype ."

tests = ["pytest", "typed-tests", "coverage-tests", "old-click-tests"]
pytest = "pytest"
typed-tests = "pytest --typeguard-packages=reportseff"
coverage-tests = "pytest --cov"
old-click-tests = { cmd = "pytest", executor = {with = ["click==6.7"]}}

coverage-xml = { cmd = "coverage xml --fail-under 0", executor = {with = ["coverage[toml]"]}}
coverage-upload = { cmd = "codecov", executor = {with = ["codecov"]}}
coverage = ["coverage-xml", "coverage-upload"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["reportseff"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.ruff.lint]
select = [ "ALL" ]

ignore = [
  "ANN401",  # allow Any
  "COM812",  # allow missing commas on last element
  "ISC001",  # recommended by format
]


[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "ANN",  # type annotations
  "S101",  # use assert
  "PLR2004",  # magic numbers in tests
  "SLF001",  # allow private methods in tests
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.10"
strict = true
warn_unused_configs = true
show_error_codes = true

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "basic"
