name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wntrblm/nox@2022.11.21
      with:
        python-versions: "3.9, 3.10, 3.11"
    - run: pipx install poetry==2.2.1
    - run: poetry self add poetry-plugin-export
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
